service: telegrambot

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-2
  role: arn:aws:iam::129060501255:role/telegram-lambda-role

plugins:
  - serverless-python-requirements

functions:
  noti:
    handler: handler.noti
    environment: 
      BOT_TOKEN: ${ssm:BOT_TOKEN}
      CHAT_ID: ${ssm:CHAT_ID}
      WEATHER_ENCODING: ${ssm:/weatherapi/encodingkey}
      WEATHER_DECODING: ${ssm:/weatherapi/decodingkey}

    events:
      - schedule: cron(30 22 * * ? *)
      # - schedule: cron(0/1 * * * ? *)
