service: telegrambot

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-2
  role: arn:aws:iam::129060501255:role/telegram-lambda-role

plugins:
  - serverless-python-requirements
  # - serverless-offline-ssm
  # - serverless-offline

functions:
  noti:
    handler: handler.noti
    environment: 
      BOT_TOKEN: ${ssm:BOT_TOKEN_ENCRPYTED}
      CHAT_ID: ${ssm:CHAT_ID}
    events:
      - schedule: cron(0 10 * * ? *)
      # - schedule: cron(0/1 * * * ? *)
